### ISSUE TITLE
paper_trail/frameworks/active_record.rb can load files out of order

### ISSUE THREAD

**Issue by tobytripp** [airblade/paper_trail#553]
A simple program with the following Gemfile:

```ruby
source "https://rubygems.org"

gem "activerecord", "4.2.2"
gem "paper_trail", "4.0.0.rc1"
gem "pg"
```

and the following code:

```ruby
#!/usr/bin/env ruby -w
require "active_record"
require "erb"
require "psych"
config = ERB.new( File.read( "config/database.yml" ) ).result binding
connection_info = Psych.load( config )["test"]
ActiveRecord::Base.establish_connection( connection_info )

require "paper_trail"

puts "LOADED!"

class CreateVersions < ActiveRecord::Migration
  def change
    create_table :items, force: true do |t|
      t.string :name
      t.timestamps
    end

    create_table :versions, force: true do |t|
      t.string   :item_type, :null => false
      t.integer  :item_id,   :null => false
      t.string   :event,     :null => false
      t.string   :whodunnit
      t.text     :object
      t.datetime :created_at
    end
    add_index :versions, [:item_type, :item_id]
  end
end

CreateVersions.new.migrate :up

class Item < ActiveRecord::Base
  has_paper_trail
end

item = Item.create name: "first"

require "pp"
pp item.versions
```

will fail to load with the following error:

```
bundle exec ruby -w error.rb
/Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/config.rb:33:in `track_associations': uninitial
ized constant PaperTrail::VersionAssociation (NameError)                                                                                    
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/version_concern.rb:14:in `block in
 <module:VersionConcern>'                                                                                                                   
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/concern.rb:120:in `class_eval'
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/activesupport-4.2.2/lib/active_support/concern.rb:120:in `append_feature
s'                                                                                                                                          
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/frameworks/active_record/models/pa
per_trail/version.rb:5:in `include'                                                                                                         
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/frameworks/active_record/models/pa
per_trail/version.rb:5:in `<class:Version>'                                                                                                 
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/frameworks/active_record/models/pa
per_trail/version.rb:4:in `<module:PaperTrail>'                                                                                             
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/frameworks/active_record/models/pa
per_trail/version.rb:3:in `<top (required)>'                                                                                                
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/frameworks/active_record.rb:4:in `
require'                                                                                                                                    
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/frameworks/active_record.rb:4:in `
block in <top (required)>'                                                                                                                  
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/frameworks/active_record.rb:3:in `
each'                                                                                                                                       
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail/frameworks/active_record.rb:3:in `
<top (required)>'                                                                                                                           
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail.rb:155:in `require'
        from /Users/toby/work/papertrail_test/bundle/ruby/2.1.0/gems/paper_trail-4.0.0.rc1/lib/paper_trail.rb:155:in `<top (required)>'
        from error.rb:3:in `require'
        from error.rb:3:in `<main>'
```

The problem seems to be that [paper_trail/frameworks/active_record.rb]
(https://github.com/airblade/paper_trail/blob/master/lib/paper_trail/frameworks/active_record.rb) tries to load `version.rb` before `PaperTrail::VersionAssociation` has been loaded.

Change [paper_trail/frameworks/active_record.rb]
(https://github.com/airblade/paper_trail/blob/master/lib/paper_trail/frameworks/active_record.rb) to:

```ruby
require "paper_trail/frameworks/active_record/models/paper_trail/version_association"
require "paper_trail/frameworks/active_record/models/paper_trail/version"
```

and the script runs without errors.

**Comment by batter** [comment]
Fixed by merge of #544 (8596968)

**Comment by batter** [comment]
Thanks for the detailed bug report / description too!

**Comment by tobytripp** [comment]
You're welcome!  It was my pleasure. 



—
Toby Tripp
