### ISSUE TITLE
reify(:has_many => true) not satisfying validation

### ISSUE THREAD

**Issue by visualizedkei** [airblade/paper_trail#572]
I have a has_many :through association between model A and model B. `reify(:has_many => true` will restore a model B's associations to model A after a destroy; however, if I add `validates :modelA, length: { minimum: 1 }` to model B, `reify(:has_many => true).save` fails and will not restore the model B. It complains "Validations failed: modelB is too short (minimum is 1 character)"

**Comment by jaredbeck** [comment]
Thanks for the bug report!  What is the minimum code that, when pasted into a new rails app, will reproduce this issue?

**Comment by visualizedkei** [comment]
models/subgroup.rb
````
class Subgroup < ActiveRecord::Base
	has_many :faqs_subgroups
	has_many :faqs, through: :faqs_subgroups
	has_paper_trail
end
````

models/faq.rb
````
class Faq < ActiveRecord::Base
	validates :subgroups, length: { minimum: 1 }
	validates_associated :subgroups
	has_many :faqs_subgroups
	has_many :subgroups, through: :faqs_subgroups
	has_paper_trail
end
````

models/faqs_subgroup.rb
````
class FaqsSubgroup < ActiveRecord::Base
	belongs_to :subgroup
	belongs_to :faq
end
````

migrate/create_faqs_subgroups.rb
````
class CreateFaqsSubgroups < ActiveRecord::Migration
  def change
    create_table :faqs_subgroups do |t|
      t.integer :faq_id, :null => false
      t.integer :subgroup_id, :null => false
      t.timestamps null: false
    end
  end
end
````

migrate/create_faqs.rb
````
class CreateFaqs < ActiveRecord::Migration
  def change
    create_table :faqs do |t|
      t.string :name
      t.timestamps null: false
    end
  end
end
````

migrate/create_subgroups.rb
````
class CreateSubgroups < ActiveRecord::Migration
  def change
    create_table :subgroups do |t|
      t.string :name
      t.timestamps null: false
    end
  end
end
````

migrate/create_versions.rb
````
class CreateVersions < ActiveRecord::Migration
  def change
    create_table :versions do |t|
      t.string   :item_type, :null => false
      t.integer  :item_id,   :null => false
      t.string   :event,     :null => false
      t.string   :whodunnit
      t.text     :object
      t.datetime :created_at
    end
    add_index :versions, [:item_type, :item_id]
  end
end
````

rails console
````
2.2.1 :001 > s = Subgroup.create!(name: "sub")
   (0.1ms)  begin transaction
  SQL (5.4ms)  INSERT INTO "subgroups" ("name", "created_at", "updated_at") VALUES (?, ?, ?)  [["name", "sub"], ["created_at", "2015-07-27 14:32:24.677204"], ["updated_at", "2015-07-27 14:32:24.677204"]]
  SQL (0.4ms)  INSERT INTO "versions" ("event", "item_id", "item_type", "created_at") VALUES (?, ?, ?, ?)  [["event", "create"], ["item_id", 1], ["item_type", "Subgroup"], ["created_at", "2015-07-27 14:32:24.746360"]]
   (53.2ms)  commit transaction
 => #<Subgroup id: 1, name: "sub", created_at: "2015-07-27 14:32:24", updated_at: "2015-07-27 14:32:24"> 
2.2.1 :002 > f = Faq.create!(name: "faq", subgroups: [s])
   (0.1ms)  begin transaction
  SQL (1.0ms)  INSERT INTO "faqs" ("name", "created_at", "updated_at") VALUES (?, ?, ?)  [["name", "faq"], ["created_at", "2015-07-27 14:32:42.053846"], ["updated_at", "2015-07-27 14:32:42.053846"]]
  SQL (2.8ms)  INSERT INTO "faqs_subgroups" ("subgroup_id", "faq_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["subgroup_id", 1], ["faq_id", 1], ["created_at", "2015-07-27 14:32:42.060273"], ["updated_at", "2015-07-27 14:32:42.060273"]]
  SQL (0.3ms)  INSERT INTO "versions" ("event", "item_id", "item_type", "created_at") VALUES (?, ?, ?, ?)  [["event", "create"], ["item_id", 1], ["item_type", "Faq"], ["created_at", "2015-07-27 14:32:42.079356"]]
   (63.5ms)  commit transaction
 => #<Faq id: 1, name: "faq", created_at: "2015-07-27 14:32:42", updated_at: "2015-07-27 14:32:42"> 
2.2.1 :003 > f.destroy
   (0.3ms)  begin transaction
  SQL (1.4ms)  DELETE FROM "faqs" WHERE "faqs"."id" = ?  [["id", 1]]
DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0. (called from irb_binding at (irb):3)
  SQL (1.1ms)  INSERT INTO "versions" ("item_id", "item_type", "event", "object", "created_at") VALUES (?, ?, ?, ?, ?)  [["item_id", 1], ["item_type", "Faq"], ["event", "destroy"], ["object", "---\nid: 1\nname: faq\ncreated_at: &1 2015-07-27 14:32:42.053846542 Z\nupdated_at: *1\n"], ["created_at", "2015-07-27 14:32:45.380319"]]
  PaperTrail::Version Load (0.0ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = ? AND "versions"."item_type" = ?  ORDER BY "versions"."created_at" ASC, "versions"."id" ASC  [["item_id", 1], ["item_type", "Faq"]]
   (53.6ms)  commit transaction
 => #<Faq id: 1, name: "faq", created_at: "2015-07-27 14:32:42", updated_at: "2015-07-27 14:32:42"> 
2.2.1 :004 > Faq.all
  Faq Load (0.4ms)  SELECT "faqs".* FROM "faqs"
 => #<ActiveRecord::Relation []> 
2.2.1 :005 > Subgroup.all
  Subgroup Load (0.3ms)  SELECT "subgroups".* FROM "subgroups"
 => #<ActiveRecord::Relation [#<Subgroup id: 1, name: "sub", created_at: "2015-07-27 14:32:24", updated_at: "2015-07-27 14:32:24">]> 
2.2.1 :006 > PaperTrail::Version.find(3)
  PaperTrail::Version Load (0.1ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."id" = ? LIMIT 1  [["id", 3]]
 => #<PaperTrail::Version id: 3, item_type: "Faq", item_id: 1, event: "destroy", whodunnit: nil, object: "---\nid: 1\nname: faq\ncreated_at: &1 2015-07-27 14:3...", created_at: "2015-07-27 14:32:45"> 
2.2.1 :007 > PaperTrail::Version.find(3).reify(:has_many => true).save
  PaperTrail::Version Load (0.7ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."id" = ? LIMIT 1  [["id", 3]]
  Faq Load (0.2ms)  SELECT  "faqs".* FROM "faqs" WHERE "faqs"."id" = ? LIMIT 1  [["id", 1]]
DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0. (called from irb_binding at (irb):7)
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
 => false 
2.2.1 :008 > Faq.all
  Faq Load (0.2ms)  SELECT "faqs".* FROM "faqs"
 => #<ActiveRecord::Relation []> 
2.2.1 :009 > PaperTrail::Version.find(3).reify(:has_many => true).save!
  PaperTrail::Version Load (0.3ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."id" = ? LIMIT 1  [["id", 3]]
  Faq Load (0.1ms)  SELECT  "faqs".* FROM "faqs" WHERE "faqs"."id" = ? LIMIT 1  [["id", 1]]
DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0. (called from irb_binding at (irb):9)
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
ActiveRecord::RecordInvalid: Validation failed: Subgroups is too short (minimum is 1 character)
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/validations.rb:79:in `raise_record_invalid'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/validations.rb:43:in `save!'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/transactions.rb:291:in `block in save!'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/transactions.rb:291:in `save!'
	from (irb):9
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /home/kei/Documents/rails/papertrail/bin/rails:8:in `<top (required)>'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /home/kei/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/kei/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
````

In rails console, I created a subgroup, then a faq that is in that subgroup, and destroyed the faq. As a result, there were no faqs but the subgroup remains. Then, I called .reify(:has_many => true).save! on the destroy event, and it complains that subgroups is too short (due to the validation of subgroups length in faq.rb)

**Comment by jaredbeck** [comment]
You're missing a migration for the `version_associations` table.  You can generate that migration with 

```
bin/rails g paper_trail:install --with_associations
```

Given the code you provided, plus the missing migrations, I am unable to reproduce the `ActiveRecord::RecordInvalid` you got.

**Comment by batter** [comment]
Good catch @jaredbeck

**Comment by visualizedkei** [comment]
Oh, yes, I did forget that in this example. This is what happens when I try that command:

````
kei@kei-VirtualBox:~/Documents/rails/papertrail$ rails g  paper_trail:install --with_associations
   identical  db/migrate/20150727141043_create_versions.rb
````
It doesn't generate a version associations table. when I first had this issue, I just copied the file over from the repo, so that I have this:
````
class CreateVersionAssociations < ActiveRecord::Migration
	def self.up
		create_table :version_associations do |t|
			t.integer :version_id
			t.string :foreign_key_name, :null => false
			t.integer :foreign_key_id
		end
		add_index :version_associations, [:version_id]
		add_index :version_associations, [:foreign_key_name, :foreign_key_id], :name => 'index_version_associations_on_foreign_key'
	end

	def self.down
		remove_index :version_associations, [:version_id]
		remove_index :version_associations, :name => 'index_version_associations_on_foreign_key'
		drop_table :version_associations
	end
end
````

here are the things I ran in terminal for the sample app:
````
kei@kei-VirtualBox:~/Documents/rails/papertrail$ rails g migration CreateVersionAssociations
      invoke  active_record
      create    db/migrate/20150728173201_create_version_associations.rb
kei@kei-VirtualBox:~/Documents/rails/papertrail$ rake db:migrate
== 20150728173201 CreateVersionAssociations: migrating ========================
-- create_table(:version_associations)
   -> 0.0026s
-- add_index(:version_associations, [:version_id])
   -> 0.0010s
-- add_index(:version_associations, [:foreign_key_name, :foreign_key_id], {:name=>"index_version_associations_on_foreign_key"})
   -> 0.0011s
== 20150728173201 CreateVersionAssociations: migrated (0.0056s) ===============

kei@kei-VirtualBox:~/Documents/rails/papertrail$ rails console
Loading development environment (Rails 4.2.3)
2.2.1 :001 > s = Subgroup.create!(name: "subgroup")
   (0.2ms)  begin transaction
  SQL (4.8ms)  INSERT INTO "subgroups" ("name", "created_at", "updated_at") VALUES (?, ?, ?)  [["name", "subgroup"], ["created_at", "2015-07-28 17:33:45.768062"], ["updated_at", "2015-07-28 17:33:45.768062"]]
  SQL (0.3ms)  INSERT INTO "versions" ("event", "item_id", "item_type", "created_at") VALUES (?, ?, ?, ?)  [["event", "create"], ["item_id", 2], ["item_type", "Subgroup"], ["created_at", "2015-07-28 17:33:45.841020"]]
   (15.7ms)  commit transaction
 => #<Subgroup id: 2, name: "subgroup", created_at: "2015-07-28 17:33:45", updated_at: "2015-07-28 17:33:45"> 
2.2.1 :002 > f = Faq.create!(name: "faq", subgroups: [s])
   (4.1ms)  begin transaction
  SQL (1.1ms)  INSERT INTO "faqs" ("name", "created_at", "updated_at") VALUES (?, ?, ?)  [["name", "faq"], ["created_at", "2015-07-28 17:34:25.917998"], ["updated_at", "2015-07-28 17:34:25.917998"]]
  SQL (0.3ms)  INSERT INTO "faqs_subgroups" ("subgroup_id", "faq_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)  [["subgroup_id", 2], ["faq_id", 2], ["created_at", "2015-07-28 17:34:25.921428"], ["updated_at", "2015-07-28 17:34:25.921428"]]
  SQL (5.4ms)  INSERT INTO "versions" ("event", "item_id", "item_type", "created_at") VALUES (?, ?, ?, ?)  [["event", "create"], ["item_id", 2], ["item_type", "Faq"], ["created_at", "2015-07-28 17:34:25.932351"]]
   (14.6ms)  commit transaction
 => #<Faq id: 2, name: "faq", created_at: "2015-07-28 17:34:25", updated_at: "2015-07-28 17:34:25"> 
2.2.1 :003 > f.destroy
   (0.3ms)  begin transaction
  SQL (1.3ms)  DELETE FROM "faqs" WHERE "faqs"."id" = ?  [["id", 2]]
DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0. (called from irb_binding at (irb):3)
  SQL (0.5ms)  INSERT INTO "versions" ("item_id", "item_type", "event", "object", "created_at") VALUES (?, ?, ?, ?, ?)  [["item_id", 2], ["item_type", "Faq"], ["event", "destroy"], ["object", "---\nid: 2\nname: faq\ncreated_at: &1 2015-07-28 17:34:25.917998660 Z\nupdated_at: *1\n"], ["created_at", "2015-07-28 17:34:28.611519"]]
  PaperTrail::Version Load (0.3ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = ? AND "versions"."item_type" = ?  ORDER BY "versions"."created_at" ASC, "versions"."id" ASC  [["item_id", 2], ["item_type", "Faq"]]
   (16.7ms)  commit transaction
 => #<Faq id: 2, name: "faq", created_at: "2015-07-28 17:34:25", updated_at: "2015-07-28 17:34:25"> 
2.2.1 :004 > Faq.all
  Faq Load (0.5ms)  SELECT "faqs".* FROM "faqs"
 => #<ActiveRecord::Relation []> 
2.2.1 :005 > Subgroup.all
  Subgroup Load (0.4ms)  SELECT "subgroups".* FROM "subgroups"
 => #<ActiveRecord::Relation [#<Subgroup id: 1, name: "sub", created_at: "2015-07-27 14:32:24", updated_at: "2015-07-27 14:32:24">, #<Subgroup id: 2, name: "subgroup", created_at: "2015-07-28 17:33:45", updated_at: "2015-07-28 17:33:45">]> 
2.2.1 :006 > PaperTrail::Version.find(3)
  PaperTrail::Version Load (0.2ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."id" = ? LIMIT 1  [["id", 3]]
 => #<PaperTrail::Version id: 3, item_type: "Faq", item_id: 1, event: "destroy", whodunnit: nil, object: "---\nid: 1\nname: faq\ncreated_at: &1 2015-07-27 14:3...", created_at: "2015-07-27 14:32:45"> 
2.2.1 :007 > PaperTrail::Version.find(3).reify(:has_many => true).save!
  PaperTrail::Version Load (0.2ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."id" = ? LIMIT 1  [["id", 3]]
  Faq Load (0.2ms)  SELECT  "faqs".* FROM "faqs" WHERE "faqs"."id" = ? LIMIT 1  [["id", 1]]
DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0. (called from irb_binding at (irb):7)
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
ActiveRecord::RecordInvalid: Validation failed: Subgroups is too short (minimum is 1 character)
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/validations.rb:79:in `raise_record_invalid'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/validations.rb:43:in `save!'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/transactions.rb:291:in `block in save!'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.3/lib/active_record/transactions.rb:291:in `save!'
	from (irb):7
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /home/kei/Documents/rails/papertrail/bin/rails:8:in `<top (required)>'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/kei/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /home/kei/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/kei/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in 
````

since it's just me, I assume it's because I couldn't generate the version associations table? If so, what should I be replacing in the associations table?

p.s. just in case I created a new app, added paper_trail to gemfile, and tried the exact command
````
kei@kei-VirtualBox:~/Documents/rails/papertrail-test$ bin/rails g paper_trail:install --with-associations
      create  db/migrate/20150728174105_create_versions.rb
````

**Comment by jaredbeck** [comment]
> Oh, yes, I did forget that in this example. This is what happens when I try that command:
> 
> kei@kei-VirtualBox:~/Documents/rails/papertrail$ rails g  paper_trail:install --with_associations
>    identical  db/migrate/20150727141043_create_versions.rb
> 
> It doesn't generate a version associations table.

That's not right. After `paper_trail:install --with_associations` you should have three migration files.  What version of `paper_trail` are you using?  If you want to be using version associations, you should be using `4.0.0.rc2`.

**Comment by visualizedkei** [comment]
That's it! I didn't have `4.0.0.rc2`. Now the tables are generating and `:has_many => true` doesn't fail the validation. Sorry for bothering!

**Comment by jaredbeck** [comment]
> That's it! I didn't have 4.0.0.rc2 .. Sorry for bothering!

No worries, glad I could help.  I wish I'd thought to ask the version first :)
