### ISSUE TITLE
has_and_belongs_to_many causes error ActiveRecord::UnknownPrimaryKey

### ISSUE THREAD

**Issue by dgobaud** [airblade/paper_trail#657]
Papertrail seems to require a primary key so it breaks with has_and_belongs_to_many join tables which do not have a primary key. When saving a record it generates the below error. If the Papertrail gem is removed there is no error.

```
class Route < ActiveRecord::Base
  has_and_belongs_to_many :trucks
end

create_join_table(:routes, :trucks) do |t|
      t.index :route_id
      t.index :truck_id
      t.index [:route_id, :truck_id], :unique => true
end
```

ActiveRecord::UnknownPrimaryKey: Unknown primary key for table routes_trucks in model Route::HABTM_Trucks.

```
[
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/reflection.rb:571:in `primary_key'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/reflection.rb:319:in `active_record_primary_key'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/reflection.rb:153:in `join_keys'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association_scope.rb:99:in `last_chain_scope'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association_scope.rb:139:in `add_constraints'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association_scope.rb:39:in `scope'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association_scope.rb:5:in `scope'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association.rb:97:in `association_scope'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association.rb:86:in `scope'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/collection_association.rb:423:in `scope'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/collection_proxy.rb:37:in `initialize'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/relation/delegation.rb:106:in `new'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/relation/delegation.rb:106:in `create'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/collection_association.rb:41:in `reader'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/builder/association.rb:115:in `versions'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/paper_trail-4.0.0/lib/paper_trail/has_paper_trail.rb:192:in `clear_rolled_back_versions'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:432:in `block in make_lambda'", 
"/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:263:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:263:in `block in simple'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `block in call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `each'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:506:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_rollback_callbacks'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:322:in `rolledback!'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:69:in `rollback_records'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:147:in `rollback'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:179:in `rollback_transaction'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:186:in `rescue in within_new_transaction'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:201:in `within_new_transaction'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:291:in `save!'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/persistence.rb:51:in `create!'", "/Users/davidgobaud/Desktop/Dropbox/Yoshi/website/app/form_objects/routes/create_form_object.rb:8:in `create!'", "/Users/davidgobaud/Desktop/Dropbox/Yoshi/website/app/controllers/api/v1/routes_controller.rb:24:in `create'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in `process_action'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/metal.rb:196:in `dispatch'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_controller/metal.rb:237:in `block in action'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45:in `serve'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/rack-pjax-0.8.0/lib/rack/pjax.rb:12:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/deflater.rb:35:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/query_cache.rb:36:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:377:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/middleware/reloader.rb:73:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/web-console-2.1.2/lib/web_console/middleware.rb:37:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/request_store-1.2.0/lib/request_store/middleware.rb:8:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:116:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/puma-2.11.2/lib/puma/server.rb:507:in `handle_request'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/puma-2.11.2/lib/puma/server.rb:375:in `process_client'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/puma-2.11.2/lib/puma/server.rb:262:in `block in run'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `call'", "/Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/puma-2.11.2/lib/puma/thread_pool.rb:104:in `block in spawn_thread'"]
```

**Comment by jaredbeck** [comment]
I don't think PaperTrail has support for HABTM associations yet. Per the readme:

> PaperTrail can restore three types of associations: Has-One, Has-Many, and Has-Many-Through.

Associations are an experimental feature in 4.0.0 and I don't recommend you use them in production.

@batter can you confirm that HABTM is unsupported, and if so, do you remember why?

**Comment by dgobaud** [comment]
Is there a way to tell papertrail to ignore has_and_belongs_to_many objects?

**Comment by jaredbeck** [comment]
I'm trying to reproduce your issue, but no luck yet.  Which of your models uses PaperTrail? I'm not seeing a `has_paper_trail` call. Thanks.

**Comment by dgobaud** [comment]
here is a sample app with the bug

https://github.com/dgobaud/habtm_papertrail

see https://github.com/dgobaud/habtm_papertrail/blob/master/config/initializers/00_paper_trail.rb

to see the bug

rake db:reset
rails c
```
2.2.2 :001 > t=Truck.create!; r=Route.create(:trucks => [t])
   (0.0ms)  begin transaction
  SQL (1.3ms)  INSERT INTO "trucks" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-12-02 05:45:06.828866"], ["updated_at", "2015-12-02 05:45:06.828866"]]
  SQL (1.2ms)  INSERT INTO "versions" ("event", "created_at", "object_changes", "item_id", "item_type") VALUES (?, ?, ?, ?, ?)  [["event", "create"], ["created_at", "2015-12-02 05:45:06.828866"], ["object_changes", "---\ncreated_at:\n- \n- &1 2015-12-02 05:45:06.828866000 Z\nupdated_at:\n- \n- *1\nid:\n- \n- 1\n"], ["item_id", 1], ["item_type", "Truck"]]
  SQL (0.5ms)  UPDATE "versions" SET "transaction_id" = ? WHERE "versions"."id" = ?  [["transaction_id", 1], ["id", 1]]
   (1.3ms)  commit transaction
   (0.1ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "routes" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2015-12-02 05:45:06.897327"], ["updated_at", "2015-12-02 05:45:06.897327"]]
  SQL (0.2ms)  INSERT INTO "versions" ("event", "created_at", "object_changes", "item_id", "item_type") VALUES (?, ?, ?, ?, ?)  [["event", "create"], ["created_at", "2015-12-02 05:45:06.897327"], ["object_changes", "---\ncreated_at:\n- \n- &1 2015-12-02 05:45:06.897327000 Z\nupdated_at:\n- \n- *1\nid:\n- \n- 1\n"], ["item_id", 1], ["item_type", "Route"]]
  SQL (0.3ms)  UPDATE "versions" SET "transaction_id" = ? WHERE "versions"."id" = ?  [["transaction_id", 2], ["id", 2]]
  SQL (1.1ms)  INSERT INTO "routes_trucks" ("truck_id", "route_id") VALUES (?, ?)  [["truck_id", 1], ["route_id", 1]]
   (0.7ms)  rollback transaction
  PaperTrail::Version Load (0.3ms)  SELECT "versions".* FROM "versions" WHERE "versions"."item_id" = ? AND "versions"."item_type" = ?  ORDER BY "versions"."created_at" ASC, "versions"."id" ASC  [["item_id", 1], ["item_type", "Route"]]
ActiveRecord::UnknownPrimaryKey: Unknown primary key for table routes_trucks in model Route::HABTM_Trucks.
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/reflection.rb:571:in `primary_key'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/reflection.rb:319:in `active_record_primary_key'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/reflection.rb:153:in `join_keys'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association_scope.rb:99:in `last_chain_scope'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association_scope.rb:139:in `add_constraints'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association_scope.rb:39:in `scope'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association_scope.rb:5:in `scope'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association.rb:97:in `association_scope'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/association.rb:86:in `scope'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/collection_association.rb:423:in `scope'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/collection_proxy.rb:37:in `initialize'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/relation/delegation.rb:106:in `new'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/relation/delegation.rb:106:in `create'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/collection_association.rb:41:in `reader'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/associations/builder/association.rb:115:in `versions'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/paper_trail-4.0.0/lib/paper_trail/has_paper_trail.rb:192:in `clear_rolled_back_versions'
... 14 levels...
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:201:in `within_new_transaction'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:286:in `block in save'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:285:in `save'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/persistence.rb:34:in `create'
	from (irb):1
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/davidgobaud/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
```

**Comment by jaredbeck** [comment]
Thanks for the sample app!

Your initializer is interesting.

```ruby
# config/initializers/paper_trail_extension.rb
ActiveRecord::Base.module_eval do
  class << self
    def inherited_with_paper_trail subclass
      # remember to skip it on SchemaMigration which has its own version method
      skipped_models = [
        "ActiveRecord::SchemaMigration",
        "PaperTrail::Version",
        "ActiveRecord::SessionStore::Session"
      ]
      inherited_without_paper_trail subclass
      unless skipped_models.include?(subclass.to_s)
        subclass.send(:has_paper_trail)
      end
    end
    alias_method_chain :inherited, :paper_trail
  end
end
```

I've never seen an initializer like this.  If I understand it correctly, it has a similar effect to the following:

```ruby
class Route < ActiveRecord::Base
  has_paper_trail
end

class Truck < ActiveRecord::Base
  has_paper_trail
end

class Route::HABTM_Trucks < ActiveRecord::Base
  has_paper_trail
end

class Truck::HABTM_Trucks < ActiveRecord::Base
  has_paper_trail
end
```

I may be missing something, since I've never seen an initializer like that, but one possible solution is:

```diff
diff --git a/app/models/route.rb b/app/models/route.rb
index 148b691..36d5fef 100644
--- a/app/models/route.rb
+++ b/app/models/route.rb
@@ -1,3 +1,4 @@
 class Route < ActiveRecord::Base
+  has_paper_trail
   has_and_belongs_to_many :trucks
 end
diff --git a/app/models/truck.rb b/app/models/truck.rb
index 61d7120..eceb17a 100644
--- a/app/models/truck.rb
+++ b/app/models/truck.rb
@@ -1,3 +1,4 @@
 class Truck < ActiveRecord::Base
+  has_paper_trail
   has_and_belongs_to_many :trucks
 end
diff --git a/config/initializers/00_paper_trail.rb b/config/initializers/00_paper_trail.rb
deleted file mode 100644
index 57b7501..0000000
--- a/config/initializers/00_paper_trail.rb
+++ /dev/null
@@ -1,14 +0,0 @@
-# config/initializers/paper_trail_extension.rb
-ActiveRecord::Base.module_eval do
-  class << self
-    def inherited_with_paper_trail subclass
-      # remember to skip it on SchemaMigration which has its own version method
-      skipped_models = ["ActiveRecord::SchemaMigration", "PaperTrail::Version", "ActiveRecord::SessionStore::Session"]
-      inherited_without_paper_trail subclass
-      unless skipped_models.include?(subclass.to_s)
-        subclass.send(:has_paper_trail)
-      end
-    end
-    alias_method_chain :inherited, :paper_trail
-  end
-end
```

**Comment by dgobaud** [comment]
Yeah it adds papertrail to every model - that would actually be a nice builtin feature :) I got it here http://stackoverflow.com/questions/16972114/apply-papertrail-to-all-models

so you basically remove has_paper_trail from the join table? Seems like I could also add it to the skipped_models list.

Is the general idea that paper_trail can't track the join table?

**Comment by jaredbeck** [comment]
> Seems like I could also add it to the skipped_models list.

I tried that in your sample app and it didn't work for me, but you may have better luck.

> Is the general idea that paper_trail can't track the join table?

Correct. I don't think PaperTrail has support for HABTM associations yet.

> .. it adds papertrail to every model - that would actually be a nice builtin feature ..

It's a tempting idea, because it would be convenient for simple apps, but the instant you needed to configure one model differently than the others you'd have to turn that feature off. I think it's better to be explicit.

**Comment by dgobaud** [comment]
Instead of having to turn the feature off there could be a way to opt-out a single model - sort of like the skipped_models list is supposed to do with the above code. Basically default on with a way to opt out vs. default off with way to opt in. User can pick the default that applies to most of their models.

**Comment by batter** [comment]
@jaredbeck - You are correct, HABTM reification / storage is not supported. The reason why is because it was not built out by the author of the PR who built out the foundation for association support, presumably because it adds a lot of complexity and would be difficult to track due to the nature of the through model in the database that supports the HABTM not having an actual ActiveRecord model class in an application in most cases.
