### ISSUE TITLE
uninitialized constant PaperTrail::Model::InstanceMethods::ActiveRecordError

### ISSUE THREAD

**Issue by KoRMaK** [airblade/paper_trail#663]
Using Rails 3.2.19
Ruby 2.0.0
Papertrail 4.0.0

I have a model with the following papertrail related stuff on it:

````
#some_model.rb
has_and_belongs_to_many :security_roles, after_add: :touch_with_version, after_remove: :touch_with_version
has_paper_trail :meta => { :item_title => Proc.new{ |item| item.data_changed},
                             :other_data => Proc.new{ |item| {:security_role_names => item.security_role_names} } }
````

When I try to create one of them using FactoryGirl, I get the following error. It's as if PaperTrail "forgets" ActiveRecordError and mistakenly thinks it should have a definition for it? 

This only happens when trying to create an item via FactoryGirl.

````
NameError: uninitialized constant PaperTrail::Model::InstanceMethods::ActiveRecordError
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/paper_trail-4.0.0/lib/paper_trail/has_paper_trail.rb:269:in `touch_with_version'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:507:in `block in callback'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:504:in `each'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:504:in `callback'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:352:in `add_to_target'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:495:in `block in concat_records'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:493:in `each'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:493:in `concat_records'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:132:in `concat'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:481:in `replace_records'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:314:in `replace'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:72:in `ids_writer'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/activerecord-3.2.19/lib/active_record/associations/builder/collection_association.rb:71:in `block in define_writers'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/factory_girl-4.4.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/factory_girl-4.4.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
	from /home/corey/.rvm/gems/ruby-2.0.0-p643@catalyst/gems/factory_girl-4.4.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
````

**Comment by jaredbeck** [comment]
Thanks for the bug report. Per the [contributing guide][2], can you please use our [bug report template][1]?

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb
[2]: https://github.com/airblade/paper_trail/blob/master/CONTRIBUTING.md

**Comment by KoRMaK** [comment]
Sure! I need some help understanding how to use the template though. Am I filling that out and running it in a console and reporting back the results, or am I filling it out with the relevant stuff for my context and pasting that in here?

**Comment by jaredbeck** [comment]
> .. filling it out with the relevant stuff for my context and pasting that in here?

Yes, that one. :) Thanks! It will help us reproduce your issue.

**Comment by jaredbeck** [comment]
Corey, were you able to prepare a bug report using the template?

I have a hunch this is a simple fix, something like the following, but we could really use a failing test from you.

```diff
- raise ActiveRecordError, "can not touch on a new record object" unless persisted?
+ raise ::ActiveRecord::ActiveRecordError, "can not touch on a new record object" unless persisted?
```

**Comment by jaredbeck** [comment]
I tried to reproduce your issue, but I wasn't able to.  Here's what I tried: https://gist.github.com/jaredbeck/91a7d4fc4528878bca06

I'm going to close this, but please let me know if you can reproduce the issue using our [bug report template][1].  Thanks.

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb
