### ISSUE TITLE
Compatibility with Rails Engines after 4.0

### ISSUE THREAD

**Issue by tfwright** [airblade/paper_trail#766]
Hi, thanks for your work on this very useful gem.

I have a Rails engine with some models, some of which I was using PaperTrail to track, which in turn I was then using in several related Rails apps. After upgrading from Rails 4.1 to 4.2 and PaperTrail 3.0 to 4.1 I ran into all sorts of issues. To try and track down the root of the problem, I created a fresh postgres-backed engine/app at those versions with nothing but a PaperTrail tracked model, and it doesn't seem to work. I get the following error: `NameError: uninitialized constant TrackedResource::PaperTrail::Version`

The docs don't mention anything about using PaperTrail with an engine, but this was working like a dream before I upgraded. Any suggestions?

Here is the demo engine and app: https://github.com/tfwright/paper_trail_engine_test

The relevant engine files:
https://github.com/tfwright/paper_trail_engine_test/blob/master/test_engine/paper_trail_engine_test.gemspec
https://github.com/tfwright/paper_trail_engine_test/blob/master/test_engine/config/initializers/active_record.rb

App:
https://github.com/tfwright/paper_trail_engine_test/blob/master/test_app/app/controllers/tracked_resources_controller.rb
https://github.com/tfwright/paper_trail_engine_test/blob/master/test_app/test/controllers/tracked_resources_controller_test.rb

Thanks!

**Comment by jaredbeck** [comment]
> I get the following error: NameError: uninitialized constant TrackedResource::PaperTrail::Version

Please provide the complete stack trace, thanks.

**Comment by tfwright** [comment]
```
NameError: uninitialized constant TrackedResource::PaperTrail::Version
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/inheritance.rb:158:in `compute_type'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/reflection.rb:295:in `compute_class'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/reflection.rb:291:in `klass'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/associations/association.rb:118:in `klass'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:41:in `reader'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activerecord-4.2.6/lib/active_record/associations/builder/association.rb:115:in `versions'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/paper_trail-4.1.0/lib/paper_trail/has_paper_trail.rb:194:in `clear_rolled_back_versions'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in `block in make_lambda'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:263:in `call'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:263:in `block in simple'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `call'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `block in call'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `each'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:506:in `call'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_rollback_callbacks'
... 15 levels...
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/tfwright/code/paper_trail_engine_test/test_app/bin/rails:9:in `<top (required)>'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/tfwright/.rbenv/versions/2.1.8/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by tfwright** [comment]
For now I have found a workaround of copying `paper_trail/version.rb` and `paper_trail/version_association.rb` into my engine's app/model directory.

**Comment by batter** [comment]
@tfwright - Are you absolutely sure that you have PaperTrail in that projects Gemfile? You are getting an uninitialized constant error which indicates you may not have the library required yet..

Maybe you can pop into a console session and execute `defined?(PaperTrail)`.

If so, can you try modifying your `has_paper_trail` declaration to pass in `class_name: '::PaperTrail::Version` and see if that fixes your issue, [like this demonstrates](https://github.com/airblade/paper_trail/tree/v4.1.0#custom-version-classes)

@jaredbeck - This seems like an unusual case, but if that doesn't work we may need to fiddle with [this line](https://github.com/airblade/paper_trail/blob/v4.1.0/lib/paper_trail/frameworks/rails/engine.rb#L4)... wondering if we might experiment with changing it to look more like this:

```ruby
paths['app/models'] << 'paper_trail/frameworks/active_record/models'
```

**Comment by tfwright** [comment]
@batter It's in the engine gemspec. Gems listed there aren't automatically required, no, which means I had to do so explicitly in an initializer. (The files are linked above). PaperTrail is definitely loaded--the has_paper_trail class method works fine. It's just the model files that don't seem to load, so `PaperTrail::Version` and `PaperTrail::VersionAssociation` are undefined.

For the record, I agree with you that there is probably an issue with adding the path like that when it's in the context of a Rails engine instead of an app.

**Comment by jaredbeck** [comment]
It's been a month with no activity on this issue. Do you guys want to keep it open a bit longer? I am not familiar with `paths['app/models']` so I can't comment on that yet. Floyd, how can we use your demo app to reproduce this issue?

**Comment by tfwright** [comment]
@jaredbeck it's been a while but I think you should be able to run tests on the demo app and see the failure.

**Comment by jaredbeck** [comment]
According to the [Engines Guide][1], section "6.6 Other Gem Dependencies",

> .. if you want to immediately require dependencies when the engine is
> required, you should require them before the engine's initialization. For
> example:
> 
> ```
> require 'other_engine/engine'
> require 'yet_another_engine/engine'
>  
> module MyEngine
>   class Engine < ::Rails::Engine
>   end
> end
> ```

Per these instructions, the following patch fixes your test application:

```diff
--- a/test_engine/lib/paper_trail_engine_test/engine.rb
+++ b/test_engine/lib/paper_trail_engine_test/engine.rb
@@ -1,3 +1,5 @@
+require "paper_trail"
+
 module PaperTrailEngineTest
   class Engine < ::Rails::Engine
   end
```

I don't think we need to make any changes to PT to support your use-case. Thanks for the issue report!

[1]: http://guides.rubyonrails.org/engines.html#other-gem-dependencies
