### ISSUE TITLE
`with_versioning` block doesn't work depending on randomized seed in Rspec

### ISSUE THREAD

**Issue by devonestes** [airblade/paper_trail#790]
We noticed some random failures in our test suite today, and after some digging we realized that depending on which seed the specs were randomized with, the `with_versioning` block seems to not work. Here is the spec that is failing:

```ruby
# frozen_string_literal: true
require 'rails_helper'

describe USACUtils::Form471ImportTool do
  before(:all) do
    with_versioning do
      path = Rails.root.join('spec', 'fixtures').to_s
      described_class.new(path: path).import_state('AK')
      described_class.new(path: path).import_state('AL')
      make_esh_edits
      described_class.new(path: File.join(path, 'updated')).import_state('AK')
    end
  end

  def make_esh_edits
    byebug
    Form471.find_by(application_number: '161000175')
           .update(applicant_address: 'AK Highway Mile Post 1380')
  end

  it 'creates the correct number of objects in our database' do
    expect(USAC::BasicInformation.count).to eq 20
    expect(USAC::Consultant.count).to eq 15
    expect(USAC::DiscountCalculation.count).to eq 103
    expect(USAC::Frn.count).to eq 40
    expect(USAC::FrnLineItem.count).to eq 65
    expect(USAC::RecipientsOfService.count).to eq 290
    expect(USAC::ConnectivityInformation.count).to eq 86
    expect(Form471.count).to eq USAC::BasicInformation.count
    expect(LineItem.count).to eq USAC::FrnLineItem.count
    expect(Allocation.count).to eq USAC::RecipientsOfService.count
  end

  context 'Basic Informations' do
    let(:bi) { USAC::BasicInformation.find_by(application_number: '161000969') }
    let(:form471) { Form471.find_by(application_number: bi.application_number) }
    let(:esh_updated) { Form471.find_by(application_number: '161000175') }

    it 'accurately imports data for basic informations' do
      expect(bi.postal_cd).to eq 'AK'
      expect(bi.billed_entity_address_1)
        .to eq '118-B West International Airport Road'
      expect(bi.billed_entity_city).to eq 'ANCHORAGE'
      expect(bi.nickname).to eq 'Fiscal Year 17 SLD FY16'
      expect(bi.billed_entity_number).to eq '145618'
      expect(bi.contact_email).to eq 'dniedermeyer@aleutregion.org'
      expect(bi.certified_timestamp).to eq '02/27/2016 10:51 AM'
    end

    it 'correctly maps basic informations to form471s' do
      expect(form471).to_not be nil
      expect(form471.applicant_name).to eq bi.billed_entity_name
      expect(form471.applicant_address).to eq bi.billed_entity_address_1
    end

    context 'USAC edited data' do
      it 'does not add a usac_updated tag if it is not esh edited' do
        expect(form471.tags.pluck(:label).empty?).to be true
      end

      it 'adds a usac_updated tag if it is esh_edited' do
        expect(esh_updated.tags.pluck(:label)).to include 'usac_updated'
      end

      it 'does not update the esh object if it is esh_edited' do
        expect(esh_updated.versions.count).to be > 0
        expect(esh_updated.applicant_address).to eq 'AK Highway Mile Post 1380'
        expect(esh_updated.basic_information.billed_entity_address_1)
          .to eq 'AK Highway Mile Post 1381'
      end
    end
  end

  it 'accurately imports data for consultants' do
    c = USAC::Consultant.find_by(application_number: '161008978')
    expect(c.postal_cd).to eq 'AK'
    expect(c.name).to eq 'Valerie Oliver'
    expect(c.consultant_registration_number).to eq '17002356'
    expect(c.city).to eq 'Anchorage,'
    expect(c.state).to eq 'AK'
    expect(c.email).to eq 'Valerie.oliver@alaska.gov'
  end

  it 'accurately imports data for discount calculations' do
    dc = USAC::DiscountCalculation.find_by(child_entity_ben: '230785')
    expect(dc.postal_cd).to eq 'AK'
    expect(dc.application_number).to eq '161000969'
    expect(dc.parent_entity_type).to eq 'School District'
    expect(dc.parent_entity_name).to eq 'ALEUTIAN REGION SCHOOL DIST'
    expect(dc.parent_entity_ben).to eq '145618'
    expect(dc.parent_state_lea_id).to eq '04'
    expect(dc.child_entity_type).to eq 'School'
    expect(dc.child_entity_name).to eq 'YAKOV E. NETSVETOV SCHOOL'
    expect(dc.child_state_school_id).to eq '040020'
    expect(dc.child_number_of_students).to eq '12'
  end

  it 'accurately imports data for frns' do
    frn = USAC::Frn.find_by(frn: '1699000508')
    expect(frn.postal_cd).to eq 'AK'
    expect(frn.application_number).to eq '161000175'
    expect(frn.service_type).to eq 'Data Transmission and/or Internet Access'
    expect(frn.establishing_fcc_form470).to eq '160006024'
    expect(frn.award_date).to eq '02/04/2016'
    expect(frn.service_provider_name)
      .to eq 'Dry Creek Internet and Communications LLC.'
    expect(frn.total_monthly_recurring_charges).to eq '6250.0'
    expect(frn.total_one_time_charges).to eq '471900.0'
  end

  context 'FRN Line Items' do
    let(:frn_li) { USAC::FrnLineItem.find_by(line_item: '1699000508.001') }
    let(:li) { LineItem.find_by(frn_complete: frn_li.line_item) }
    # rubocop:disable Metrics/LineLength
    it 'accurately imports data for frn line items' do
      expect(frn_li.postal_cd).to eq 'AK'
      expect(frn_li.application_number).to eq '161000175'
      expect(frn_li.frn).to eq '1699000508'
      expect(frn_li.function).to eq 'Wireless'
      expect(frn_li.type_of_product).to eq 'Microwave'
      expect(frn_li.purpose).to eq 'Internet access service that includes a connection from any applicant site directly to the Internet Service Provider'
      expect(frn_li.connection_used_by).to eq 'One building/site listed'
      expect(frn_li.monthly_recurring_unit_costs).to eq '6250.0'
      expect(frn_li.monthly_quantity).to eq '1'
      expect(frn_li.total_monthly_eligible_recurring_costs).to eq '6250.0'
    end
    # rubocop:enable Metrics/LineLength

    it 'correctly maps frn line items to line items' do
      expect(li).to_not be nil
      expect(li.application_number).to eq frn_li.application_number
    end
  end

  context 'Recipients of Services' do
    let(:rs) do
      USAC::RecipientsOfService
        .find_by(line_item: '1699000508.001', ben: '17001469')
    end

    let(:allocation) do
      Allocation.find_by(frn_complete: rs.line_item, recipient_ben: rs.ben)
    end

    it 'accurately imports data for recipients of service' do
      expect(rs.postal_cd).to eq 'AK'
      expect(rs.name).to eq 'Living Word Academy'
      expect(rs.quantity).to eq '1.0'
      expect(rs.application_number).to eq '161000175'
      expect(rs.frn).to eq '1699000508'
      expect(rs.amount).to be nil
    end

    it 'correctly maps recipients of services to allocations' do
      expect(allocation).to_not be nil
      expect(allocation.recipient_name).to eq rs.name
    end
  end

  it 'accurately imports data for connectivity information' do
    ci = USAC::ConnectivityInformation
         .find_by(child_entity_number: '230785')
    expect(ci.postal_cd).to eq 'AK'
    expect(ci.child_entity_name).to eq 'YAKOV E. NETSVETOV SCHOOL'
    expect(ci.application_number).to eq '161006093'
    expect(ci.parent_entity_name).to eq 'ALEUTIAN REGION SCHOOL DIST'
    expect(ci.parent_entity_number).to eq '145618'
    expect(ci.child_download_speed).to eq '10.0'
    expect(ci.child_wifi).to eq 'Mostly'
    expect(ci.child_connection_type).to eq 'Other'
    expect(ci.child_biggest_barriers)
      .to eq 'Inconsistent service/frequent outages and down time'
  end

  after(:all) do
    [
      USAC::BasicInformation, USAC::Consultant, USAC::DiscountCalculation,
      USAC::Frn, USAC::FrnLineItem, USAC::RecipientsOfService,
      USAC::ConnectivityInformation, LineItemCircuit, Form471, LineItem,
      Allocation, Version, OtherLocation, Entity, EntityBen, Tag, Note
    ].each(&:delete_all)
  end
end
```

And here's the terminal output for the test runs, including checking the number of `Version` objects in our test database at the same point in execution.

```
> be rspec --seed=20015

Randomized with seed 20015
...........................................................................................................................................................................................................................
[13, 22] in /Users/devoncestes/esh/IRT/spec/lib/utils/usac_utils/form471_import_tool_spec.rb
   13:   end
   14:
   15:   def make_esh_edits
   16:     byebug
   17:     Form471.find_by(application_number: '161000175')
=> 18:            .update(applicant_address: 'AK Highway Mile Post 1380')
   19:   end
   20:
   21:   it 'creates the correct number of objects in our database' do
   22:     expect(USAC::BasicInformation.count).to eq 20
(byebug) Version.count
946
(byebug) continue
.....................................................................................................................................

Finished in 41.81 seconds (files took 5.03 seconds to load)
352 examples, 0 failures

Randomized with seed 20015

> be rspec --seed=20014

Randomized with seed 20014
...............................................................................................................................................................................................................................................................
[13, 22] in /Users/devoncestes/esh/IRT/spec/lib/utils/usac_utils/form471_import_tool_spec.rb
   13:   end
   14:
   15:   def make_esh_edits
   16:     byebug
   17:     Form471.find_by(application_number: '161000175')
=> 18:            .update(applicant_address: 'AK Highway Mile Post 1380')
   19:   end
   20:
   21:   it 'creates the correct number of objects in our database' do
   22:     expect(USAC::BasicInformation.count).to eq 20
(byebug) Version.count
0
(byebug) continue
.......F.F.......................................................................................

Failures:

  1) USACUtils::Form471ImportTool Basic Informations USAC edited data adds a usac_updated tag if it is esh_edited
     Failure/Error: expect(esh_updated.tags.pluck(:label)).to include 'usac_updated'
       expected [] to include "usac_updated"
     # ./spec/lib/utils/usac_utils/form471_import_tool_spec.rb:62:in `block (4 levels) in <top (required)>'

  2) USACUtils::Form471ImportTool Basic Informations USAC edited data does not update the esh object if it is esh_edited
     Failure/Error: expect(esh_updated.versions.count).to be > 0

       expected: > 0
            got:   0
     # ./spec/lib/utils/usac_utils/form471_import_tool_spec.rb:66:in `block (4 levels) in <top (required)>'

Finished in 40.27 seconds (files took 5.05 seconds to load)
352 examples, 2 failures

Failed examples:

rspec ./spec/lib/utils/usac_utils/form471_import_tool_spec.rb:61 # USACUtils::Form471ImportTool Basic Informations USAC edited data adds a usac_updated tag if it is esh_edited
rspec ./spec/lib/utils/usac_utils/form471_import_tool_spec.rb:65 # USACUtils::Form471ImportTool Basic Informations USAC edited data does not update the esh object if it is esh_edited

Randomized with seed 20014
```

I've noticed that if I change the `before(:all)` block to a `before(:each)` block then it works, but that _drastically_ slows down our test suite, so that's not a reasonable solution for the long term.

We're using ruby 2.3.0 and PaperTrail 4.0.0.

I also can't really write a failing test for this since it's a transient error, but hopefully the above info will be enough. I know it's going to be exceedingly hard to reproduce this bug, but if there's anything I can do to help please let me know!

**Comment by jaredbeck** [comment]
> I also can't really write a failing test for this since it's a transient error, but hopefully the above info will be enough. I know it's going to be exceedingly hard to reproduce this bug, but if there's anything I can do to help please let me know!

Please try to write a script to reproduce this using our [bug report template][1]. Even if it doesn't happen every time we run it, having such a script will be very helpful.

[1]: https://github.com/airblade/paper_trail/blob/master/doc/bug_report_template.rb

**Comment by devonestes** [comment]
Sure thing, I'll see if I can get it to work.

**Comment by jaredbeck** [comment]
Hi Devon, Have you been able to reproduce this issue with a script? Do you want me to keep this issue open a little while longer?

**Comment by devonestes** [comment]
I put an hour into it but I haven't yet been able to reproduce the issue outside of our repo, so I think it'll just have to be closed. I'll keep thinking of ways to reproduce it with a script though, and if I can get that to happen then I'll open a new issue with the script included.

**Comment by jaredbeck** [comment]
Thanks for trying!

**Comment by zauzaj** [comment]
@devonestes Hi, I'm experiencing same issue during randomized specs. How did you solve yours at the end? 

Thanks a lot
