### ISSUE TITLE
Suport saving Change Set only

### ISSUE THREAD

**Issue by eshaiju** [airblade/paper_trail#824]
In my current project, we only need to know which changed the object and what are the changes. For this  we only need object_changes. Tried removing object column, but that  throwing error,

```
  NoMethodError - undefined method `type' for nil:NilClass:
  paper_trail (3.0.9) lib/paper_trail/version_concern.rb:94:in `object_col_is_json?'
  paper_trail (3.0.9) lib/paper_trail/has_paper_trail.rb:116:in `serialize_attributes_for_paper_trail'
  paper_trail (3.0.9) lib/paper_trail/has_paper_trail.rb:361:in `block in object_attrs_for_paper_trail'
  paper_trail (3.0.9) lib/paper_trail/has_paper_trail.rb:360:in `object_attrs_for_paper_trail'
  paper_trail (3.0.9) lib/paper_trail/has_paper_trail.rb:280:in `record_update'
  activesupport (4.2.6) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.6) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
  activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `call'
```

**Comment by jaredbeck** [comment]
> .. we only need object_changes .. Tried removing object column, but that throwing error ..

Hi Shaiju. The database column `versions.object` is required. I don't think it can be optional, because it is used by `reify`, among other things.
