### ISSUE TITLE
NoMethodError - private method `after_create' called

### ISSUE THREAD

**Issue by Matrisis** [airblade/paper_trail#867]
Hello,

I recently upgraded some of my gems.
Now i have this problem for only one of my models using paper_trail:
```ruby
NoMethodError - private method `after_create' called for #<Class:0x007fc4a4617cc0>
Did you mean?  after_update:
  activerecord (4.2.7.1) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  paper_trail (5.2.2) lib/paper_trail/model_config.rb:34:in `on_create'
  paper_trail (5.2.2) lib/paper_trail/model_config.rb:146:in `block in setup_callbacks_from_options'
  paper_trail (5.2.2) lib/paper_trail/model_config.rb:145:in `setup_callbacks_from_options'
  paper_trail (5.2.2) lib/paper_trail/model_config.rb:78:in `setup'
  paper_trail (5.2.2) lib/paper_trail/has_paper_trail.rb:65:in `has_paper_trail'
  app/models/subscription_setting.rb:4:in `<class:SubscriptionSetting>'
  app/models/subscription_setting.rb:1:in `<top (required)>'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:457:in `block in load_file'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:647:in `new_constants_in'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:456:in `load_file'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:354:in `require_or_load'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:494:in `load_missing_constant'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:184:in `const_missing'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:526:in `load_missing_constant'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:184:in `const_missing'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:526:in `load_missing_constant'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:184:in `const_missing'
  app/views/layouts/_header.html.erb:32:in 
...
```

My model: 
```ruby
class SubscriptionSetting < ActiveRecord::Base
  acts_as_singleton

  has_paper_trail
  validates :trial_duration, :notice_period, presence: true

  validates_numericality_of :trial_duration, :notice_period, greater_than: -1
end
```

I run with: 
ruby 2.3.0
Rails 4.2.7.1
paper_trail (5.2.2)

Thank you.

**Comment by jaredbeck** [comment]
Hi Matthieu. If you remove `acts_as_singleton` do you still have this issue? Thanks.

**Comment by Matrisis** [comment]
Hi Jared, thank you for your quick answer.

It seems that `acts_as_singleton` was effectively the problem.
I placed `acts_as_singleton` under `has_paper_trail` and it solved the problem.

```ruby
class SubscriptionSetting < ActiveRecord::Base

  has_paper_trail
  acts_as_singleton
  validates :trial_duration, :notice_period, presence: true

  validates_numericality_of :trial_duration, :notice_period, greater_than: -1
end
```

**Comment by jaredbeck** [comment]
Thanks Matthieu, I'm glad you found a workaround.

Looking at [acts_as_singleton.rb][2], it changes the accessibility of certain methods, making them private. Because `acts_as_singleton` changes the AR interface, PT cannot support it.

Note to self: It looks like the [acts_as_singleton gem][1] has not been updated in over four years (most recent: 0.0.8 - 2012-05-18)

[1]: https://rubygems.org/gems/acts_as_singleton
[2]: https://github.com/stephencelis/acts_as_singleton/blob/master/lib/acts_as_singleton.rb
